spring:
  application:
    name: loginapp
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/loginapp
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
